// leave off @2x/@3x
const images = {
  //ICON
  home: require('../Images/Icons/ic-home.png'),
  splash : require('../Images/splash.png'),
  logo_menu: require('../Images/Icons/logo-menu.png'),
  logoJobr: require('../Images/Icons/logo.png'),
  menu: require('../Images/Icons/Menu.png'),
  card: require('../Images/Icons/ic-card.png'),
  cardActive: require('../Images/Icons/ic-card-active.png'),
  activities: require('../Images/Icons/ic-activities.png'),
  activitiesActive: require('../Images/Icons/ic-activities-active.png'),
  notification: require('../Images/Icons/ic-notification.png'),
  notificationActive: require('../Images/Icons/ic-notification-active.png'),
  profile: require('../Images/Icons/ic-profile.png'),
  profileActive: require('../Images/Icons/ic-profile-active.png'),
  facebook: require('../Images/Icons/ic-facebook.png'),
  icFacebook: require('../Images/Icons/logo-fb-simple.png'),
  google: require('../Images/Icons/ic-google.png'),
  apple: require('../Images/Icons/ic-apple.png'),
  email: require('../Images/Icons/ic-email.png'),
  mail: require('../Images/Icons/mail.png'),
  password: require('../Images/Icons/ic-password.png'),
  back: require('../Images/Icons/ic-back.png'),
  backBlack: require('../Images/Icons/ic-back-black.png'),
  name: require('../Images/Icons/ic-name.png'),
  tooNow: require('../Images/Icons/ic-too-now.png'),
  male: require('../Images/Icons/ic-male.png'),
  female: require('../Images/Icons/ic-female.png'),
  unselect: require('../Images/Icons/ic-confirm-no.png'),
  select: require('../Images/Icons/ic-confirm-yes.png'),
  camera: require('../Images/Icons/ic-camera.png'),
  gps: require('../Images/Icons/ic-gps.png'),
  myPosition: require('../Images/Icons/ic-my-position.png'),
  calendar: require('../Images/Icons/calendar.png'),
  search: require('../Images/Icons/ic-search.png'),
  phone: require('../Images/Icons/ic-phone.png'),
  circlePrimary: require('../Images/Icons/ic-circle-primary.png'),
  marketIcon: require('../Images/Icons/ic-market.png'),
  confirmYes: require('../Images/Icons/ic-confirm-yes.png'),
  confirmNo: require('../Images/Icons/ic-confirm-no.png'),
  startWhite: require('../Images/Icons/ic-star-white.png'),
  starOrange: require('../Images/Icons/orange-star.png'),
  addItem: require('../Images/Icons/add-item.png'),
  visa: require('../Images/Icons/ic-visa.png'),
  masterCard: require('../Images/Icons/ic-masterCard.png'),
  masterCardVR: require('../Images/Icons/ic-masterCard-vr.png'),
  message: require('../Images/Icons/ic-message.png'),
  toPosition: require('../Images/Icons/ic-to-position.png'),
  line: require('../Images/Icons/line.png'),
  starActive: require('../Images/Icons/ic-star-active.png'),
  // starInactive: require('../Images/Icons/ic-star-inactive.png'),
  question: require('../Images/Icons/question.png'),
  acceptCall: require('../Images/Icons/ic-accept-call.png'),
  calling: require('../Images/Icons/ic-calling.png'),
  changeCamera: require('../Images/Icons/ic-change-camera.png'),
  declineCall: require('../Images/Icons/ic-decline-call.png'),
  offCamera: require('../Images/Icons/ic-off-camera.png'),
  offMicro: require('../Images/Icons/ic-off-micro.png'),
  onCamera: require('../Images/Icons/ic-on-camera.png'),
  onMicro: require('../Images/Icons/ic-on-micro.png'),
  warning: require('../Images/Icons/ic-warning.png'),
  cameraBorder: require('../Images/Icons/camera-border.png'),
  chatButton: require('../Images/Icons/chat-button.png'),
  cart: require('../Images/Icons/ic-cart.png'),
  directionLine: require('../Images/Icons/direction-line.png'),
  stepLineYes: require('../Images/Icons/step-line-yes.png'),
  stepLineNo: require('../Images/Icons/step-line-no.png'),
  changePriceIcon: require('../Images/Icons/change-price.png'),
  darkLine: require('../Images/Icons/dark-line.png'),
  selectImage: require('../Images/Icons/ic-select-image.png'),
  send: require('../Images/Icons/ic-send.png'),
  zoomIn: require('../Images/Icons/ic-zoom-in.png'),
  phoneCall: require('../Images/Icons/ic-phone-call.png'),
  findingJobr: require('../Images/Icons/ic-finding-jobr.png'),
  findJobrFailed: require('../Images/Icons/ic-find-jobr-failed.png'),
  grayClose: require('../Images/Icons/gray-close.png'),
  logoPrimary: require('../Images/Icons/logo_primary.png'),
  icBlueJobr: require('../Images/Icons/ic-blue-jobr.png'),
  icFacebook: require('../Images/Icons/logo-fb-simple.png'),
  apple: require('../Images/Icons/ic-apple.png'),
  mail: require('../Images/Icons/mail.png'),
  shapeRight: require('../Images/Icons/right-shape.png'),
  grayShapeRight: require('../Images/Icons/gray-shape-right.png'),
  circleBack: require('../Images/Icons/circle-back-icon.png'),
  location: require('../Images/Icons/ic-location.png'),
  locationRadius: require('../Images/Icons/location-radius.png'),
  icDrop: require('../Images/Icons/ic-drop.png'),
  exclamationIc: require('../Images/Icons/exclamation-ic.png'),
  greenTick: require('../Images/Icons/green-tick.png'),
  purpleLocation: require('../Images/Icons/location.png'),
  purpleStar: require('../Images/Icons/purple-star.png'),
  purpleCamera: require('../Images/Icons/purple-camera.png'),
  actorIcon: require('../Images/Icons/actor-ic.png'),
  chatIc: require('../Images/Icons/chat-button-ic.png'),
  exclamationIc: require('../Images/Icons/exclamation-ic.png'),
  chatAbout: require('../Images/Icons/chat-icon-about.png'),
  appstoreIc: require('../Images/Icons/appstore-ic.png'),
  CHplayIc: require('../Images/Icons/CH-play-ic.png'),
  mailAbout: require('../Images/Icons/mail-about.png'),
  byke: require('../Images/Icons/byke.png'),
  flagIc: require('../Images/Icons/flag-ic.png'),
  priceTags: require('../Images/Icons/price-tags.png'),
  purpleLocationRadius: require('../Images/Icons/purple-location.png'),
  purpleStore: require('../Images/Icons/purple-store.png'),
  whiteRightShape: require('../Images/Icons/right-white.png'),
  ic_arrow_back: require('../Images/Icons/ic_arrow_back.png'),
  ic_arrow_next: require('../Images/Icons/ic_arrow_next.png'),
  purpleAddButton: require('../Images/Icons/purple-add-button.png'),
  purpleShapeRight: require('../Images/Icons/purple-shape-right.png'),
  purpleCash: require('../Images/Icons/purple-cash.png'),
  switchIcon: require('../Images/Icons/switch-icon.png'),
  blackPriceTags: require('../Images/Icons/black-price-tags.png'),
  graySelect: require('../Images/Icons/icon-gray-select.png'),
  redClose: require('../Images/Icons/icon-red-close-border.png'),
  icPersonWon: require('../Images/Icons/ic_person_won.png'),
  ic_destination: require('../Images/Icons/ic_destination.png'),
  ic_origin: require('../Images/Icons/ic_origin.png'),
  ic_my_location: require('../Images/Icons/ic_my_location.png'),

  //IMAGES
  logo: require('../Images/logo-white.png'),
  profileDefault: require('../Images/img-profile.jpeg'),
  empty: require('../Images/img-empty.png'),
  market: require('../Images/img-market.jpg'),
  market2: require('../Images/img-market2.jpg'),
  bgLogin: require('../Images/bg-login.png'),
  bgWelcome1: require('../Images/bg-welcome-1.png'),
  bgWelcome2: require('../Images/bg-welcome-2.png'),
  bgWelcome3: require('../Images/bg-welcome-3.png'),
  congratulation: require('../Images/bg-congratulation.png'),
  bgMap: require('../Images/bg-map.png'),
  bgTop: require('../Images/bg-top.png'),
  bgTopAskr: require('../Images/bg-top-askr.png'),
  bgToolBar: require('../Images/bg-toolbar-profile.png'),
  bgMapOrderTracking: require('../Images/bg-map-order-tracking.png'),
  bgCalling: require('../Images/bg-calling.png'),
  bgFindingJobrBottom: require('../Images/bg-finding-jobr-bottom.png'),
  bgFindingJobrTop: require('../Images/bg-finding-jobr-top.png'),
  bgJobrHome: require('../Images/bg-jobr-home.png'),
  welcomeBackground: require('../Images/background-toonow-jobr.png'),
  signupSuccess : require('../Images/signup_success.png'),
  jobrSplash : require('../Images/Jobr_Splash.png'),
  noMission : require('../Images/no-mission.png'),
  welcome_1 : require('../Images/new_welcome_1.png'),
  welcome_2 : require('../Images/new_welcome_2.png'),
  welcome_3 : require('../Images/new_welcome_3.png'),
  done: require('../Images/Icons/done.png'),
  next: require('../Images/Icons/next.png'),
  icNext:require('../Images/Icons/ic-next.png'),
  backIcon : require('../Images/Icons/back-icon.png'),
  plus : require('../Images/Icons/plus.png'),
  close : require('../Images/Icons/close.png'),
  check: require('../Images/Icons/check.png'),
  cart: require('../Images/Icons/cart.png'),
  online: require('../Images/Icons/video.png'),
  service: require('../Images/Icons/service.png'),
  delivery: require('../Images/Icons/delivery.png'),
  online : require('../Images/Icons/video.png'),
  shopping: require('../Images/Icons/cart.png'),
  delivery : require('../Images/Icons/delivery.png'),
  service : require('../Images/Icons/service.png'),
  plus: require('../Images/Icons/plus-icon.png'),
  videoCall : require('../Images/Icons/video-call.png')

  // clearLogo: require('../Images/top_logo.png'),
  // launch: require('../Images/launch-icon.png'),
  // ready: require('../Images/your-app.png'),
  // ignite: require('../Images/ignite_logo.png'),
  // igniteClear: require('../Images/ignite-logo-transparent.png'),
  // tileBg: require('../Images/tile_bg.png'),
  // background: require('../Images/BG.png'),
  // buttonBackground: require('../Images/button-bg.png'),
  // api: require('../Images/Icons/icon-api-testing.png'),
  // components: require('../Images/Icons/icon-components.png'),
  // deviceInfo: require('../Images/Icons/icon-device-information.png'),
  // faq: require('../Images/Icons/faq-icon.png'),
  // home: require('../Images/Icons/icon-home.png'),
  // theme: require('../Images/Icons/icon-theme.png'),
  // usageExamples: require('../Images/Icons/icon-usage-examples.png'),
  // chevronRight: require('../Images/Icons/chevron-right.png'),
  // hamburger: require('../Images/Icons/hamburger.png'),
  // backButton: require('../Images/Icons/back-button.png'),
  // closeButton: require('../Images/Icons/close-button.png')
}

export default images
